import type {
  User,
  Organization,
  Patient,
  Facility,
  Placement,
  DashboardStats,
  FacilityDashboardStats,
  SuperAdminDashboardStats,
  Referral,
  ActivityEvent,
} from "@/types";

// ── Organizations ──

export const organizations: Organization[] = [
  {
    id: "org-001",
    name: "Mercy Hospital Portland",
    slug: "mercy-hospital-portland",
    type: "hospital",
  },
  {
    id: "org-002",
    name: "Providence Health System",
    slug: "providence-health",
    type: "hospital",
  },
  {
    id: "org-003",
    name: "OHSU Health",
    slug: "ohsu-health",
    type: "hospital",
  },
];

// ── Current User ──

export const currentUser: User = {
  id: "usr-001",
  email: "sjohnson@mercyhospital.org",
  firstName: "Sarah",
  lastName: "Johnson",
  role: "social-worker",
  title: "Senior Social Worker",
  department: "Discharge Planning",
  hospitalId: "hosp-001",
  organizationId: "org-001",
  phone: "(555) 234-5678",
  createdAt: "2024-09-01T08:00:00Z",
  updatedAt: "2026-07-01T12:00:00Z",
};

// ── Patients ──

export const patients: Patient[] = [
  {
    id: "pat-001",
    mrn: "MRN-88472",
    firstName: "Eleanor",
    lastName: "Roosevelt",
    dateOfBirth: "1942-03-15",
    age: 84,
    gender: "female",
    address: {
      street: "42 Maple Avenue",
      city: "Portland",
      state: "OR",
      zipCode: "97201",
      county: "Multnomah",
    },
    phone: "(503) 555-1212",
    emergencyContact: {
      name: "James Roosevelt",
      role: "Son",
      phone: "(503) 555-3434",
      email: "james.r@email.com",
    },
    insurance: [
      {
        provider: "Medicare Part A & B",
        policyNumber: "MED-88472-A",
        type: "medicare",
        status: "verified",
      },
    ],
    primaryDiagnosis: "Hip fracture (post-surgical)",
    secondaryDiagnoses: ["Hypertension", "Type 2 diabetes", "Osteoporosis"],
    careLevelRequired: "skilled-nursing",
    notes: "Patient lives alone. Two-story home with stairs. Requires 6-8 weeks of rehab post-hip replacement.",
    socialWorkerId: "usr-001",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    admissionDate: "2026-06-28T14:30:00Z",
    estimatedDischargeDate: "2026-07-10T00:00:00Z",
    status: "ready-for-discharge",
    createdAt: "2026-06-28T14:30:00Z",
    updatedAt: "2026-07-07T09:00:00Z",
  },
  {
    id: "pat-002",
    mrn: "MRN-89103",
    firstName: "George",
    lastName: "Washington",
    dateOfBirth: "1938-07-22",
    age: 87,
    gender: "male",
    address: {
      street: "1888 Liberty Street",
      city: "Portland",
      state: "OR",
      zipCode: "97204",
    },
    phone: "(503) 555-9876",
    emergencyContact: {
      name: "Martha Washington",
      role: "Daughter",
      phone: "(503) 555-5656",
      email: "martha.w@email.com",
    },
    insurance: [
      {
        provider: "Medicare Advantage",
        policyNumber: "MA-89103-B",
        type: "medicare",
        status: "active",
      },
      {
        provider: "Aetna Supplemental",
        policyNumber: "AET-44567",
        type: "private",
        status: "verified",
      },
    ],
    primaryDiagnosis: "Cerebrovascular accident (CVA) - Ischemic stroke",
    secondaryDiagnoses: ["Atrial fibrillation", "Hyperlipidemia", "History of TIA"],
    careLevelRequired: "rehabilitation",
    notes: "Right-sided weakness. Needs intensive PT/OT. Unable to return home without 24/7 support.",
    socialWorkerId: "usr-001",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    admissionDate: "2026-07-01T11:00:00Z",
    estimatedDischargeDate: "2026-07-15T00:00:00Z",
    status: "assessment-in-progress",
    createdAt: "2026-07-01T11:00:00Z",
    updatedAt: "2026-07-06T16:00:00Z",
  },
  {
    id: "pat-003",
    mrn: "MRN-90345",
    firstName: "Maria",
    lastName: "Garcia",
    dateOfBirth: "1955-11-02",
    age: 70,
    gender: "female",
    address: {
      street: "750 Cedar Lane",
      city: "Beaverton",
      state: "OR",
      zipCode: "97005",
      county: "Washington",
    },
    phone: "(503) 555-3344",
    emergencyContact: {
      name: "Carlos Garcia",
      role: "Spouse",
      phone: "(503) 555-2233",
      email: "carlos.g@email.com",
    },
    insurance: [
      {
        provider: "Blue Cross Blue Shield",
        policyNumber: "BCBS-77203",
        type: "private",
        status: "verified",
      },
    ],
    primaryDiagnosis: "COPD exacerbation",
    secondaryDiagnoses: ["Congestive heart failure", "Sleep apnea", "Obesity"],
    careLevelRequired: "home-health",
    notes: "Lives with spouse who works during day. Needs home health for oxygen management and daily monitoring. Home is accessible - single level.",
    socialWorkerId: "usr-001",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    admissionDate: "2026-07-03T09:00:00Z",
    estimatedDischargeDate: "2026-07-12T00:00:00Z",
    status: "assessment-in-progress",
    createdAt: "2026-07-03T09:00:00Z",
    updatedAt: "2026-07-07T11:00:00Z",
  },
  {
    id: "pat-004",
    mrn: "MRN-91456",
    firstName: "Robert",
    lastName: "Frost",
    dateOfBirth: "1948-12-26",
    age: 77,
    gender: "male",
    address: {
      street: "112 Woodland Path",
      city: "Gresham",
      state: "OR",
      zipCode: "97030",
    },
    phone: "(503) 555-7788",
    emergencyContact: {
      name: "Emily Frost",
      role: "Daughter",
      phone: "(503) 555-9900",
      email: "emily.f@email.com",
    },
    insurance: [
      {
        provider: "Medicare Part A",
        policyNumber: "MED-91456-A",
        type: "medicare",
        status: "active",
      },
    ],
    primaryDiagnosis: "Alzheimer's disease (advanced)",
    secondaryDiagnoses: ["Malnutrition", "Dehydration", "Urinary tract infection"],
    careLevelRequired: "long-term-care",
    notes: "Wandering risk. Requires 24/7 supervised care. Family unable to provide necessary level of support at home.",
    socialWorkerId: "usr-001",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    admissionDate: "2026-07-05T16:00:00Z",
    status: "admitted",
    createdAt: "2026-07-05T16:00:00Z",
    updatedAt: "2026-07-06T10:00:00Z",
  },
  {
    id: "pat-005",
    mrn: "MRN-92789",
    firstName: "Yuki",
    lastName: "Tanaka",
    dateOfBirth: "1963-05-18",
    age: 63,
    gender: "female",
    address: {
      street: "890 Cherry Blossom Drive",
      city: "Portland",
      state: "OR",
      zipCode: "97219",
    },
    phone: "(503) 555-4455",
    emergencyContact: {
      name: "Ken Tanaka",
      role: "Brother",
      phone: "(503) 555-6677",
      email: "ken.t@email.com",
    },
    insurance: [
      {
        provider: "Providence Health Plan",
        policyNumber: "PHP-55678",
        type: "private",
        status: "verified",
      },
    ],
    primaryDiagnosis: "Spinal cord injury - L1 fracture",
    secondaryDiagnoses: ["Neurogenic bladder", "Chronic back pain"],
    careLevelRequired: "rehabilitation",
    notes: "Full-time wheelchair user. Home needs modification. Requires intensive inpatient rehab before discharge planning.",
    socialWorkerId: "usr-001",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    admissionDate: "2026-07-01T08:30:00Z",
    estimatedDischargeDate: "2026-08-01T00:00:00Z",
    status: "admitted",
    createdAt: "2026-07-01T08:30:00Z",
    updatedAt: "2026-07-05T14:00:00Z",
  },
];

// ── Facilities ──

export const facilities: Facility[] = [
  {
    id: "fac-001",
    name: "Willamette Valley Rehabilitation Center",
    type: "rehabilitation-center",
    address: {
      street: "4500 Health Way",
      city: "Portland",
      state: "OR",
      zipCode: "97210",
      county: "Multnomah",
    },
    phone: "(503) 555-1000",
    email: "admissions@willametterehab.org",
    website: "https://willametterehab.org",
    contacts: [
      {
        name: "Patricia Moore",
        role: "Admissions Director",
        phone: "(503) 555-1001",
        email: "pmoore@willametterehab.org",
      },
    ],
    licensure: ["OR-DHS-8821", "CARF-Accredited"],
    accreditations: ["CARF", "Joint Commission"],
    capacity: 120,
    currentOccupancy: 98,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross", "Providence", "Aetna"],
    careLevelsOffered: ["skilled-nursing", "rehabilitation"],
    specialties: ["Orthopedic rehab", "Stroke recovery", "Cardiac rehab", "Neurological rehab"],
    rating: 4.5,
    reviewsCount: 128,
    hasAvailability: true,
    waitlistDays: 3,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-001",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "fac-002",
    name: "St. Francis Assisted Living Community",
    type: "assisted-living",
    address: {
      street: "2200 Peaceful Drive",
      city: "Portland",
      state: "OR",
      zipCode: "97202",
      county: "Multnomah",
    },
    phone: "(503) 555-2000",
    email: "info@stfranciscare.org",
    contacts: [
      {
        name: "Michael Chen",
        role: "Executive Director",
        phone: "(503) 555-2001",
        email: "mchen@stfranciscare.org",
      },
    ],
    licensure: ["OR-DHS-6634"],
    accreditations: ["Joint Commission"],
    capacity: 80,
    currentOccupancy: 72,
    insuranceAccepted: ["Medicare", "Private Pay", "Long-term care insurance"],
    careLevelsOffered: ["independent-living", "assisted-living", "memory-care"],
    specialties: ["Memory care", "Alzheimer's care", "Medication management"],
    rating: 4.3,
    reviewsCount: 94,
    hasAvailability: true,
    waitlistDays: 14,
    acceptsMedicare: true,
    acceptsMedicaid: false,
    organizationId: "org-001",
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "fac-003",
    name: "Columbia River Skilled Nursing Facility",
    type: "skilled-nursing-facility",
    address: {
      street: "890 River Road",
      city: "Portland",
      state: "OR",
      zipCode: "97217",
      county: "Multnomah",
    },
    phone: "(503) 555-3000",
    email: "admissions@columbiasnf.org",
    contacts: [
      {
        name: "David Williams",
        role: "Director of Nursing",
        phone: "(503) 555-3001",
        email: "dwilliams@columbiasnf.org",
      },
      {
        name: "Amanda Torres",
        role: "Admissions Coordinator",
        phone: "(503) 555-3002",
        email: "atorres@columbiasnf.org",
      },
    ],
    licensure: ["OR-DHS-4412", "CMS-Certified"],
    accreditations: ["Joint Commission", "AHCA"],
    capacity: 150,
    currentOccupancy: 145,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross", "Aetna", "Cigna"],
    careLevelsOffered: ["skilled-nursing", "long-term-care", "rehabilitation"],
    specialties: ["Wound care", "Post-surgical recovery", "Palliative care", "IV therapy"],
    rating: 4.1,
    reviewsCount: 203,
    hasAvailability: false,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-001",
    createdAt: "2022-09-01T00:00:00Z",
    updatedAt: "2026-07-02T00:00:00Z",
  },
  {
    id: "fac-004",
    name: "Healing Hearts Home Health Agency",
    type: "home-health-agency",
    address: {
      street: "555 Care Lane",
      city: "Beaverton",
      state: "OR",
      zipCode: "97005",
      county: "Washington",
    },
    phone: "(503) 555-4000",
    email: "care@healinghearts.org",
    contacts: [
      {
        name: "Rachel Green",
        role: "Clinical Director",
        phone: "(503) 555-4001",
        email: "rgreen@healinghearts.org",
      },
    ],
    licensure: ["OR-DHS-3341", "CHAP-Accredited"],
    accreditations: ["CHAP", "BBB"],
    capacity: 200,
    currentOccupancy: 165,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross", "Providence"],
    careLevelsOffered: ["home-health", "hospice"],
    specialties: ["Wound care", "Infusion therapy", "Palliative care", "Physical therapy", "Occupational therapy"],
    rating: 4.7,
    reviewsCount: 67,
    hasAvailability: true,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-001",
    createdAt: "2023-03-15T00:00:00Z",
    updatedAt: "2026-06-30T00:00:00Z",
  },
  {
    id: "fac-005",
    name: "Sunrise Memory Care Center",
    type: "assisted-living",
    address: {
      street: "1200 Sunrise Boulevard",
      city: "Gresham",
      state: "OR",
      zipCode: "97030",
      county: "Multnomah",
    },
    phone: "(503) 555-5000",
    email: "info@sunrisememory.org",
    contacts: [
      {
        name: "Lisa Park",
        role: "Community Relations",
        phone: "(503) 555-5001",
        email: "lpark@sunrisememory.org",
      },
    ],
    licensure: ["OR-DHS-7712"],
    accreditations: ["Alzheimer's Association Certified"],
    capacity: 60,
    currentOccupancy: 58,
    insuranceAccepted: ["Medicare", "Medicaid", "Private Pay"],
    careLevelsOffered: ["assisted-living", "long-term-care"],
    specialties: ["Alzheimer's care", "Dementia care", "Behavioral management"],
    rating: 4.4,
    reviewsCount: 41,
    hasAvailability: true,
    waitlistDays: 21,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-001",
    createdAt: "2023-11-01T00:00:00Z",
    updatedAt: "2026-07-05T00:00:00Z",
  },
];

// ── Placements ──

export const placements: Placement[] = [
  {
    id: "plc-001",
    patientId: "pat-001",
    facilityId: "fac-003",
    socialWorkerId: "usr-001",
    status: "pending-approval",
    careLevel: "skilled-nursing",
    priority: "high",
    assessmentNotes: "Patient requires 24/7 nursing care for wound management and post-surgical monitoring. Hip replacement recovery expected 6-8 weeks.",
    preferredLocation: {
      city: "Portland",
      state: "OR",
      maxDistanceMiles: 20,
    },
    matchedFacilities: ["fac-003", "fac-001"],
    selectedFacilityId: "fac-003",
    insurancePreAuthorized: true,
    notes: "Columbia River SNF has bed available starting 7/11. Family has toured and approved.",
    organizationId: "org-001",
    createdAt: "2026-07-02T10:00:00Z",
    updatedAt: "2026-07-07T14:00:00Z",
  },
  {
    id: "plc-002",
    patientId: "pat-002",
    socialWorkerId: "usr-001",
    status: "searching",
    careLevel: "rehabilitation",
    priority: "high",
    assessmentNotes: "Stroke patient needing intensive PT/OT. Right-sided hemiparesis. Good rehab potential.",
    preferredLocation: {
      city: "Portland",
      state: "OR",
      maxDistanceMiles: 15,
    },
    matchedFacilities: ["fac-001", "fac-003"],
    insurancePreAuthorized: false,
    notes: "Waiting on insurance pre-authorization. Willamette Valley Rehab has expressed interest.",
    organizationId: "org-001",
    createdAt: "2026-07-03T09:00:00Z",
    updatedAt: "2026-07-07T11:00:00Z",
  },
  {
    id: "plc-003",
    patientId: "pat-003",
    socialWorkerId: "usr-001",
    status: "assessment",
    careLevel: "home-health",
    priority: "medium",
    assessmentNotes: "COPD patient stable for home with supportive services. Needs daily nursing visits and oxygen management.",
    preferredLocation: {
      city: "Beaverton",
      state: "OR",
      maxDistanceMiles: 10,
    },
    matchedFacilities: ["fac-004"],
    insurancePreAuthorized: true,
    notes: "Healing Hearts can start home health services upon discharge. Spouse trained on oxygen equipment.",
    organizationId: "org-001",
    createdAt: "2026-07-05T14:00:00Z",
    updatedAt: "2026-07-07T09:00:00Z",
  },
];

// ── Dashboard Stats ──

export const dashboardStats: DashboardStats = {
  activePatients: patients.length,
  activePlacements: placements.length,
  pendingAssessments: patients.filter((p) => p.status === "assessment-in-progress").length,
  facilitiesAvailable: facilities.filter((f) => f.hasAvailability).length,
  placementsThisMonth: 12,
  averagePlacementTimeDays: 3.5,
};

// ── Activity Feed ──

// ── Facility Users ──

export const facilityUsers: User[] = [
  {
    id: "usr-fac-001",
    email: "pmoore@willametterehab.org",
    firstName: "Patricia",
    lastName: "Moore",
    role: "facility-coordinator",
    title: "Admissions Director",
    department: "Admissions",
    hospitalId: "fac-001",
    organizationId: "org-001",
    phone: "(503) 555-1001",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "usr-fac-002",
    email: "mchen@stfranciscare.org",
    firstName: "Michael",
    lastName: "Chen",
    role: "facility-coordinator",
    title: "Executive Director",
    department: "Administration",
    hospitalId: "fac-002",
    organizationId: "org-001",
    phone: "(503) 555-2001",
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2026-06-28T00:00:00Z",
  },
];

// ── Referrals (for Facility Operators) ──

export const referrals: Referral[] = [
  {
    id: "ref-001",
    patientName: "Eleanor Roosevelt",
    patientAge: 84,
    careLevel: "skilled-nursing",
    referringHospital: "Mercy Hospital Portland",
    referringHospitalId: "hosp-001",
    referredBy: "Sarah Johnson",
    referredAt: "2026-07-06T10:00:00Z",
    status: "reviewing",
    notes: "Post-surgical hip replacement. Needs 24/7 nursing care for wound management. Estimated 6-8 week stay.",
    diagnosis: "Hip fracture (post-surgical)",
    insuranceInfo: "Medicare Part A & B",
  },
  {
    id: "ref-002",
    patientName: "George Washington",
    patientAge: 87,
    careLevel: "rehabilitation",
    referringHospital: "Mercy Hospital Portland",
    referringHospitalId: "hosp-001",
    referredBy: "Sarah Johnson",
    referredAt: "2026-07-05T14:00:00Z",
    status: "new",
    notes: "Stroke patient with right-sided weakness. Needs intensive PT/OT. Good rehab potential.",
    diagnosis: "Cerebrovascular accident (CVA) - Ischemic stroke",
    insuranceInfo: "Medicare Advantage, Aetna Supplemental",
  },
  {
    id: "ref-003",
    patientName: "Robert Frost",
    patientAge: 77,
    careLevel: "long-term-care",
    referringHospital: "Mercy Hospital Portland",
    referringHospitalId: "hosp-001",
    referredBy: "Sarah Johnson",
    referredAt: "2026-07-05T16:00:00Z",
    status: "new",
    notes: "Advanced Alzheimer's patient. Wandering risk. Requires 24/7 supervised memory care.",
    diagnosis: "Alzheimer's disease (advanced)",
    insuranceInfo: "Medicare Part A",
  },
  {
    id: "ref-004",
    patientName: "Maria Garcia",
    patientAge: 70,
    careLevel: "home-health",
    referringHospital: "Mercy Hospital Portland",
    referringHospitalId: "hosp-001",
    referredBy: "Sarah Johnson",
    referredAt: "2026-07-04T09:00:00Z",
    status: "accepted",
    notes: "COPD patient stable for home with supportive services. Needs daily nursing visits and oxygen management.",
    diagnosis: "COPD exacerbation",
    insuranceInfo: "Blue Cross Blue Shield",
  },
  {
    id: "ref-005",
    patientName: "Yuki Tanaka",
    patientAge: 63,
    careLevel: "rehabilitation",
    referringHospital: "Mercy Hospital Portland",
    referringHospitalId: "hosp-001",
    referredBy: "Sarah Johnson",
    referredAt: "2026-07-03T11:00:00Z",
    status: "declined",
    notes: "Spinal cord injury patient. Full-time wheelchair user. Facility not equipped for extended neuro-rehab.",
    diagnosis: "Spinal cord injury - L1 fracture",
    insuranceInfo: "Providence Health Plan",
  },
];

// ── Facility Dashboard Stats ──

export const facilityDashboardStats: FacilityDashboardStats = {
  currentOccupancy: 98,
  totalCapacity: 120,
  availableBeds: 22,
  pendingReferrals: referrals.filter((r) => r.status === "new" || r.status === "reviewing").length,
  pendingAdmissions: 3,
  upcomingDischarges: 5,
  placementsThisMonth: 18,
  averageStayDays: 34,
  occupancyRate: Math.round((98 / 120) * 100),
};

// ── All Users (for Super Admin) ──

export const allUsers: User[] = [
  {
    id: "usr-001",
    email: "sjohnson@mercyhospital.org",
    firstName: "Sarah",
    lastName: "Johnson",
    role: "social-worker",
    title: "Senior Social Worker",
    department: "Discharge Planning",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    phone: "(555) 234-5678",
    createdAt: "2024-09-01T08:00:00Z",
    updatedAt: "2026-07-01T12:00:00Z",
  },
  {
    id: "usr-002",
    email: "jdoe@mercyhospital.org",
    firstName: "James",
    lastName: "Doe",
    role: "discharge-planner",
    title: "Discharge Planner",
    department: "Discharge Planning",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    phone: "(555) 234-5679",
    createdAt: "2024-10-15T08:00:00Z",
    updatedAt: "2026-06-15T12:00:00Z",
  },
  {
    id: "usr-003",
    email: "asmith@mercyhospital.org",
    firstName: "Amanda",
    lastName: "Smith",
    role: "administrator",
    title: "Department Administrator",
    department: "Discharge Planning",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    phone: "(555) 234-5680",
    createdAt: "2023-03-01T08:00:00Z",
    updatedAt: "2026-07-05T12:00:00Z",
  },
  {
    id: "usr-fac-001",
    email: "pmoore@willametterehab.org",
    firstName: "Patricia",
    lastName: "Moore",
    role: "facility-coordinator",
    title: "Admissions Director",
    department: "Admissions",
    hospitalId: "fac-001",
    organizationId: "org-001",
    phone: "(503) 555-1001",
    createdAt: "2024-01-15T00:00:00Z",
    updatedAt: "2026-07-01T00:00:00Z",
  },
  {
    id: "usr-fac-002",
    email: "mchen@stfranciscare.org",
    firstName: "Michael",
    lastName: "Chen",
    role: "facility-coordinator",
    title: "Executive Director",
    department: "Administration",
    hospitalId: "fac-002",
    organizationId: "org-001",
    phone: "(503) 555-2001",
    createdAt: "2023-06-01T00:00:00Z",
    updatedAt: "2026-06-28T00:00:00Z",
  },
  {
    id: "usr-admin-001",
    email: "admin@carebridgehealth.com",
    firstName: "Admin",
    lastName: "User",
    role: "superadmin",
    title: "System Administrator",
    department: "Operations",
    hospitalId: "hosp-001",
    organizationId: "org-001",
    phone: "(555) 000-0001",
    createdAt: "2023-01-01T08:00:00Z",
    updatedAt: "2026-07-08T12:00:00Z",
  },
];

// ── All Hospitals (for Super Admin) ──

export const allHospitals = [
  { id: "hosp-001", name: "Mercy Hospital Portland", city: "Portland", state: "OR", phone: "(503) 555-0100", npi: "1234567890", organizationId: "org-001" },
  { id: "hosp-002", name: "Providence St. Vincent Medical Center", city: "Portland", state: "OR", phone: "(503) 555-0200", npi: "1234567891", organizationId: "org-002" },
  { id: "hosp-003", name: "Oregon Health & Science University", city: "Portland", state: "OR", phone: "(503) 555-0300", npi: "1234567892", organizationId: "org-003" },
  { id: "hosp-004", name: "Legacy Emanuel Medical Center", city: "Portland", state: "OR", phone: "(503) 555-0400", npi: "1234567893", organizationId: "org-001" },
];

// ── Super Admin Dashboard Stats ──

export const superAdminDashboardStats: SuperAdminDashboardStats = {
  totalUsers: allUsers.length,
  totalHospitals: allHospitals.length,
  totalFacilities: facilities.length,
  totalPlacements: 47,
  activePlacements: placements.length,
  completedPlacements: 38,
  usersByRole: {
    "social-worker": 1,
    "discharge-planner": 1,
    "administrator": 1,
    "facility-coordinator": 2,
    "superadmin": 1,
  },
  placementsByMonth: [
    { month: "Feb", count: 5 },
    { month: "Mar", count: 8 },
    { month: "Apr", count: 6 },
    { month: "May", count: 10 },
    { month: "Jun", count: 12 },
    { month: "Jul", count: 6 },
  ],
  averagePlacementTimeDays: 3.5,
  facilityUtilizationRate: 82,
  pendingApprovals: 3,
};

// ── Placements History (for Super Admin) ──

export const allPlacements: Placement[] = [
  ...placements,
  {
    id: "plc-004",
    patientId: "pat-004",
    facilityId: "fac-002",
    socialWorkerId: "usr-001",
    status: "completed",
    careLevel: "long-term-care",
    priority: "high",
    matchedFacilities: ["fac-002", "fac-005"],
    selectedFacilityId: "fac-002",
    insurancePreAuthorized: true,
    notes: "Patient placed at St. Francis Memory Care unit.",
    organizationId: "org-001",
    createdAt: "2026-06-01T10:00:00Z",
    updatedAt: "2026-06-15T14:00:00Z",
    completedDate: "2026-06-15T14:00:00Z",
  },
  {
    id: "plc-005",
    patientId: "pat-005",
    socialWorkerId: "usr-001",
    status: "in-progress",
    careLevel: "rehabilitation",
    priority: "medium",
    matchedFacilities: ["fac-001"],
    selectedFacilityId: "fac-001",
    insurancePreAuthorized: true,
    notes: "Ongoing intensive rehab at Willamette Valley Rehab. Progressing well.",
    organizationId: "org-001",
    createdAt: "2026-06-20T09:00:00Z",
    updatedAt: "2026-07-05T14:00:00Z",
    startDate: "2026-06-22T00:00:00Z",
  },
];

// ── Activity Feed ──

export const recentActivity: ActivityEvent[] = [
  {
    id: "act-001",
    type: "placement",
    title: "Placement pending approval",
    description: "Eleanor Roosevelt's placement at Columbia River SNF submitted for approval.",
    patientName: "Eleanor Roosevelt",
    patientId: "pat-001",
    timestamp: "2026-07-07T14:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
  {
    id: "act-002",
    type: "assessment",
    title: "Assessment completed",
    description: "Maria Garcia assessed for home health needs. Healing Hearts recommended.",
    patientName: "Maria Garcia",
    patientId: "pat-003",
    timestamp: "2026-07-07T09:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
  {
    id: "act-003",
    type: "milestone",
    title: "Insurance verified",
    description: "George Washington's Aetna supplemental coverage confirmed for inpatient rehab.",
    patientName: "George Washington",
    patientId: "pat-002",
    timestamp: "2026-07-06T16:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
  {
    id: "act-004",
    type: "admission",
    title: "New patient admitted",
    description: "Robert Frost admitted for advanced Alzheimer's care assessment.",
    patientName: "Robert Frost",
    patientId: "pat-004",
    timestamp: "2026-07-05T16:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
  {
    id: "act-005",
    type: "placement",
    title: "Facilities matched",
    description: "3 skilled nursing facilities matched for Eleanor Roosevelt's care needs.",
    patientName: "Eleanor Roosevelt",
    patientId: "pat-001",
    timestamp: "2026-07-04T11:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
  {
    id: "act-006",
    type: "note",
    title: "Care plan updated",
    description: "Yuki Tanaka's rehab goals updated. Extended stay recommended by PT team.",
    patientName: "Yuki Tanaka",
    patientId: "pat-005",
    timestamp: "2026-07-05T14:00:00Z",
    userId: "usr-001",
    organizationId: "org-001",
  },
];
