import type { Facility, CareLevel, FacilityType } from "@/types";

const FACILITIES: Facility[] = [
  {
    id: "dummy-snf-001",
    name: "Evergreen Skilled Nursing & Rehabilitation",
    description: "A premier skilled nursing facility offering comprehensive rehabilitation services in a compassionate environment.",
    type: "skilled-nursing-facility",
    address: { street: "1200 Evergreen Blvd", city: "Portland", state: "OR", zipCode: "97201", county: "Multnomah" },
    phone: "(503) 555-0101",
    email: "admissions@evergreensnf.com",
    website: "https://evergreensnf.com",
    contacts: [{ name: "Sarah Mitchell", role: "Admissions Director", phone: "(503) 555-0102", email: "s.mitchell@evergreensnf.com" }],
    licensure: ["OR-SNF-2024-001", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["Joint Commission", "AHCA"],
    capacity: 120,
    currentOccupancy: 98,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross Blue Shield", "Aetna", "Cigna"],
    careLevelsOffered: ["skilled-nursing", "rehabilitation", "memory-care"],
    specialties: ["Post-Surgery Recovery", "Stroke Rehabilitation", "Wound Care", "IV Therapy"],
    rating: 4.5,
    reviewsCount: 87,
    hasAvailability: true,
    waitlistDays: 3,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-001",
    media: [],
    createdAt: "2024-01-15T00:00:00.000Z",
    updatedAt: "2024-06-01T00:00:00.000Z",
  },
  {
    id: "dummy-snf-002",
    name: "Cedar Hills Rehabilitation Center",
    description: "State-of-the-art rehabilitation center focused on helping patients regain independence.",
    type: "rehabilitation-center",
    address: { street: "450 Cedar Lane", city: "Portland", state: "OR", zipCode: "97202", county: "Multnomah" },
    phone: "(503) 555-0201",
    email: "info@cedarhillsrehab.com",
    website: "https://cedarhillsrehab.com",
    contacts: [{ name: "James Walker", role: "Patient Coordinator", phone: "(503) 555-0202", email: "j.walker@cedarhillsrehab.com" }],
    licensure: ["OR-REHAB-2024-015", "Medicare Certified"],
    accreditations: ["CARF", "Joint Commission"],
    capacity: 80,
    currentOccupancy: 75,
    insuranceAccepted: ["Medicare", "Aetna", "Cigna", "UnitedHealthcare", "Kaiser Permanente"],
    careLevelsOffered: ["rehabilitation", "skilled-nursing", "independent-living"],
    specialties: ["Orthopedic Rehabilitation", "Neurological Rehab", "Sports Medicine", "Aquatic Therapy"],
    rating: 4.7,
    reviewsCount: 124,
    hasAvailability: true,
    waitlistDays: 5,
    acceptsMedicare: true,
    acceptsMedicaid: false,
    organizationId: "org-dummy-002",
    media: [],
    createdAt: "2024-02-20T00:00:00.000Z",
    updatedAt: "2024-06-10T00:00:00.000Z",
  },
  {
    id: "dummy-al-001",
    name: "Sunrise Senior Living - Downtown",
    description: "Vibrant assisted living community in the heart of downtown with premium amenities and 24/7 care.",
    type: "assisted-living",
    address: { street: "800 Oak Avenue", city: "Portland", state: "OR", zipCode: "97204", county: "Multnomah" },
    phone: "(503) 555-0301",
    email: "downtown@sunrisesenior.com",
    website: "https://sunrisesenior.com/downtown",
    contacts: [{ name: "Emily Torres", role: "Community Director", phone: "(503) 555-0302", email: "e.torres@sunrisesenior.com" }],
    licensure: ["OR-AL-2024-042", "Medicaid Certified"],
    accreditations: ["LeadingAge", "ALFA"],
    capacity: 100,
    currentOccupancy: 88,
    insuranceAccepted: ["Medicaid", "Blue Cross Blue Shield", "Aetna", "Humana"],
    careLevelsOffered: ["assisted-living", "memory-care", "independent-living"],
    specialties: ["Dementia Care", "Medication Management", "Personal Care Assistance"],
    rating: 4.3,
    reviewsCount: 56,
    hasAvailability: true,
    waitlistDays: 2,
    acceptsMedicare: false,
    acceptsMedicaid: true,
    organizationId: "org-dummy-003",
    media: [],
    createdAt: "2024-03-01T00:00:00.000Z",
    updatedAt: "2024-05-15T00:00:00.000Z",
  },
  {
    id: "dummy-ltc-001",
    name: "Willamette Valley Long-Term Care Center",
    description: "Compassionate long-term care facility providing around-the-clock skilled nursing and personal care.",
    type: "long-term-care",
    address: { street: "2100 River Road", city: "Salem", state: "OR", zipCode: "97301", county: "Marion" },
    phone: "(503) 555-0401",
    email: "care@willametteltc.com",
    contacts: [{ name: "Dr. Robert Chen", role: "Medical Director", phone: "(503) 555-0402", email: "r.chen@willametteltc.com" }],
    licensure: ["OR-LTC-2024-008", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["Joint Commission"],
    capacity: 150,
    currentOccupancy: 145,
    insuranceAccepted: ["Medicare", "Medicaid", "Cigna", "UnitedHealthcare"],
    careLevelsOffered: ["long-term-care", "skilled-nursing", "hospice"],
    specialties: ["Palliative Care", "Geriatric Medicine", "Chronic Disease Management"],
    rating: 4.1,
    reviewsCount: 203,
    hasAvailability: false,
    waitlistDays: 45,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-004",
    media: [],
    createdAt: "2023-11-01T00:00:00.000Z",
    updatedAt: "2024-06-05T00:00:00.000Z",
  },
  {
    id: "dummy-hh-001",
    name: "Pacific Home Health Services",
    description: "Bringing quality home health care to patients throughout the Portland metro area.",
    type: "home-health-agency",
    address: { street: "550 Market Street", city: "Portland", state: "OR", zipCode: "97205", county: "Multnomah" },
    phone: "(503) 555-0501",
    email: "patients@pacifichomehealth.com",
    website: "https://pacifichomehealth.com",
    contacts: [
      { name: "Lisa Nguyen", role: "Clinical Director", phone: "(503) 555-0502", email: "l.nguyen@pacifichomehealth.com" },
    ],
    licensure: ["OR-HHA-2024-021", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["CHAP", "AHHA"],
    capacity: 200,
    currentOccupancy: 165,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross Blue Shield", "Aetna", "Cigna", "UnitedHealthcare", "Humana", "Kaiser Permanente"],
    careLevelsOffered: ["home-health", "skilled-nursing", "rehabilitation", "hospice"],
    specialties: ["Wound Care", "Physical Therapy", "Occupational Therapy", "Speech Therapy", "Infusion Therapy"],
    rating: 4.8,
    reviewsCount: 312,
    hasAvailability: true,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-005",
    media: [],
    createdAt: "2023-06-15T00:00:00.000Z",
    updatedAt: "2024-06-12T00:00:00.000Z",
  },
  {
    id: "dummy-hosp-001",
    name: "Serenity Hospice & Palliative Care",
    description: "Providing dignity and comfort for patients facing life-limiting illnesses.",
    type: "hospice",
    address: { street: "320 Peaceful Drive", city: "Beaverton", state: "OR", zipCode: "97005", county: "Washington" },
    phone: "(503) 555-0601",
    email: "care@serenityhospice.org",
    website: "https://serenityhospice.org",
    contacts: [{ name: "Maria Gonzalez", role: "Hospice Director", phone: "(503) 555-0602", email: "m.gonzalez@serenityhospice.org" }],
    licensure: ["OR-HOSP-2024-003", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["NHPCO", "Joint Commission"],
    capacity: 60,
    currentOccupancy: 52,
    insuranceAccepted: ["Medicare", "Medicaid", "Aetna", "Cigna", "UnitedHealthcare"],
    careLevelsOffered: ["hospice", "home-health"],
    specialties: ["End-of-Life Care", "Pain Management", "Bereavement Support", "Spiritual Care"],
    rating: 4.9,
    reviewsCount: 178,
    hasAvailability: true,
    waitlistDays: 1,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-006",
    media: [],
    createdAt: "2023-09-01T00:00:00.000Z",
    updatedAt: "2024-05-20T00:00:00.000Z",
  },
  {
    id: "dummy-snf-003",
    name: "Mt. Hood Medical Center - Transitional Care Unit",
    description: "Hospital-affiliated transitional care unit for patients stepping down from acute care.",
    type: "skilled-nursing-facility",
    address: { street: "1000 Mountain View Dr", city: "Gresham", state: "OR", zipCode: "97030", county: "Multnomah" },
    phone: "(503) 555-0701",
    email: "tcu@mthoodmedical.org",
    contacts: [{ name: "Patricia O'Brien", role: "TCU Manager", phone: "(503) 555-0702", email: "p.obrien@mthoodmedical.org" }],
    licensure: ["OR-SNF-2024-022", "Medicare Certified"],
    accreditations: ["Joint Commission", "AHCA"],
    capacity: 40,
    currentOccupancy: 38,
    insuranceAccepted: ["Medicare", "Blue Cross Blue Shield", "Cigna", "Kaiser Permanente"],
    careLevelsOffered: ["skilled-nursing", "rehabilitation"],
    specialties: ["Post-Operative Care", "Cardiac Rehabilitation", "Pulmonary Therapy"],
    rating: 4.4,
    reviewsCount: 45,
    hasAvailability: false,
    waitlistDays: 14,
    acceptsMedicare: true,
    acceptsMedicaid: false,
    organizationId: "org-dummy-007",
    media: [],
    createdAt: "2024-01-01T00:00:00.000Z",
    updatedAt: "2024-06-08T00:00:00.000Z",
  },
  {
    id: "dummy-al-002",
    name: "Maple Leaf Assisted Living & Memory Care",
    description: "Specialized assisted living with a dedicated memory care wing for residents with Alzheimer's and dementia.",
    type: "assisted-living",
    address: { street: "750 Maple Street", city: "Vancouver", state: "WA", zipCode: "98660", county: "Clark" },
    phone: "(360) 555-0801",
    email: "info@mapleleafal.com",
    contacts: [{ name: "David Kim", role: "Executive Director", phone: "(360) 555-0802", email: "d.kim@mapleleafal.com" }],
    licensure: ["WA-AL-2024-015", "Medicaid Certified"],
    accreditations: ["LeadingAge"],
    capacity: 90,
    currentOccupancy: 72,
    insuranceAccepted: ["Medicaid", "Aetna", "Humana", "UnitedHealthcare"],
    careLevelsOffered: ["assisted-living", "memory-care"],
    specialties: ["Alzheimer's Care", "Dementia Care", "Fall Prevention", "Nutrition Management"],
    rating: 4.6,
    reviewsCount: 93,
    hasAvailability: true,
    waitlistDays: 7,
    acceptsMedicare: false,
    acceptsMedicaid: true,
    organizationId: "org-dummy-008",
    media: [],
    createdAt: "2024-04-10T00:00:00.000Z",
    updatedAt: "2024-06-11T00:00:00.000Z",
  },
  {
    id: "dummy-ltc-002",
    name: "Columbia River Care Center",
    description: "Full-service long-term care facility with a focus on holistic wellness and community engagement.",
    type: "long-term-care",
    address: { street: "150 Riverfront Parkway", city: "Vancouver", state: "WA", zipCode: "98661", county: "Clark" },
    phone: "(360) 555-0901",
    email: "admissions@columbiarivercare.org",
    contacts: [{ name: "Amanda Foster", role: "Admissions Coordinator", phone: "(360) 555-0902", email: "a.foster@columbiarivercare.org" }],
    licensure: ["WA-LTC-2024-009", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["Joint Commission"],
    capacity: 130,
    currentOccupancy: 118,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross Blue Shield", "Aetna"],
    careLevelsOffered: ["long-term-care", "skilled-nursing", "rehabilitation", "hospice"],
    specialties: ["Geriatric Psychiatry", "Pain Management", "Palliative Care"],
    rating: 3.9,
    reviewsCount: 167,
    hasAvailability: true,
    waitlistDays: 10,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-009",
    media: [],
    createdAt: "2023-08-15T00:00:00.000Z",
    updatedAt: "2024-05-30T00:00:00.000Z",
  },
  {
    id: "dummy-rehab-002",
    name: "Northwest Rehabilitation Institute",
    description: "Region's leading rehabilitation institute specializing in brain injury and spinal cord recovery.",
    type: "rehabilitation-center",
    address: { street: "2000 Health Sciences Dr", city: "Seattle", state: "WA", zipCode: "98101", county: "King" },
    phone: "(206) 555-1001",
    email: "referrals@nwrehab.org",
    website: "https://nwrehab.org",
    contacts: [{ name: "Dr. Michael Torres", role: "Medical Director", phone: "(206) 555-1002", email: "m.torres@nwrehab.org" }],
    licensure: ["WA-REHAB-2024-005", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["CARF", "Joint Commission", "AAN"],
    capacity: 60,
    currentOccupancy: 58,
    insuranceAccepted: ["Medicare", "Medicaid", "Blue Cross Blue Shield", "Aetna", "Cigna", "UnitedHealthcare", "Kaiser Permanente"],
    careLevelsOffered: ["rehabilitation", "skilled-nursing", "long-term-care"],
    specialties: ["Brain Injury Rehabilitation", "Spinal Cord Injury", "Neurological Disorders", "Prosthetics"],
    rating: 4.8,
    reviewsCount: 245,
    hasAvailability: false,
    waitlistDays: 60,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-010",
    media: [],
    createdAt: "2023-04-01T00:00:00.000Z",
    updatedAt: "2024-06-15T00:00:00.000Z",
  },
  {
    id: "dummy-hh-002",
    name: "Cascade Home Health Partners",
    description: "Trusted home health agency serving families across the Portland-Vancouver metro area.",
    type: "home-health-agency",
    address: { street: "880 Cascade Plaza", city: "Portland", state: "OR", zipCode: "97206", county: "Multnomah" },
    phone: "(503) 555-1101",
    email: "care@cascadehomehealth.com",
    contacts: [{ name: "Stephanie Brooks", role: "Director of Nursing", phone: "(503) 555-1102", email: "s.brooks@cascadehomehealth.com" }],
    licensure: ["OR-HHA-2024-035", "Medicare Certified"],
    accreditations: ["CHAP"],
    capacity: 150,
    currentOccupancy: 130,
    insuranceAccepted: ["Medicare", "Blue Cross Blue Shield", "Aetna", "Cigna", "Humana"],
    careLevelsOffered: ["home-health", "hospice"],
    specialties: ["Home Health Aide", "Skilled Nursing", "Medical Social Work", "Home Infusion"],
    rating: 4.2,
    reviewsCount: 89,
    hasAvailability: true,
    acceptsMedicare: true,
    acceptsMedicaid: false,
    organizationId: "org-dummy-011",
    media: [],
    createdAt: "2024-01-20T00:00:00.000Z",
    updatedAt: "2024-06-02T00:00:00.000Z",
  },
  {
    id: "dummy-mc-001",
    name: "Heritage Memory Care Center",
    description: "Purpose-built memory care community providing specialized support for residents with cognitive impairments.",
    type: "assisted-living",
    address: { street: "420 Heritage Lane", city: "Tigard", state: "OR", zipCode: "97223", county: "Washington" },
    phone: "(503) 555-1201",
    email: "info@heritagememorycare.com",
    website: "https://heritagememorycare.com",
    contacts: [{ name: "Jennifer Park", role: "Memory Care Director", phone: "(503) 555-1202", email: "j.park@heritagememorycare.com" }],
    licensure: ["OR-AL-2024-078", "Medicaid Certified"],
    accreditations: ["LeadingAge", "ATA"],
    capacity: 50,
    currentOccupancy: 44,
    insuranceAccepted: ["Medicaid", "Humana", "UnitedHealthcare"],
    careLevelsOffered: ["memory-care", "assisted-living"],
    specialties: ["Alzheimer's Care", "Dementia Care", "Validation Therapy", "Music Therapy"],
    rating: 4.7,
    reviewsCount: 72,
    hasAvailability: true,
    waitlistDays: 8,
    acceptsMedicare: false,
    acceptsMedicaid: true,
    organizationId: "org-dummy-012",
    media: [],
    createdAt: "2024-03-15T00:00:00.000Z",
    updatedAt: "2024-06-09T00:00:00.000Z",
  },
  {
    id: "dummy-snf-004",
    name: "Portland Community Convalescent Center",
    description: "Community-focused skilled nursing facility offering short-term rehab and long-term care.",
    type: "skilled-nursing-facility",
    address: { street: "555 Community Drive", city: "Portland", state: "OR", zipCode: "97203", county: "Multnomah" },
    phone: "(503) 555-1301",
    email: "admissions@pccconvalescent.org",
    contacts: [{ name: "Harold Jenkins", role: "Administrator", phone: "(503) 555-1302", email: "h.jenkins@pccconvalescent.org" }],
    licensure: ["OR-SNF-2024-045", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["AHCA"],
    capacity: 90,
    currentOccupancy: 85,
    insuranceAccepted: ["Medicare", "Medicaid", "Cigna", "UnitedHealthcare"],
    careLevelsOffered: ["skilled-nursing", "rehabilitation", "long-term-care"],
    specialties: ["Wound Care", "Pain Management", "IV Therapy", "Post-Surgical Recovery"],
    rating: 3.8,
    reviewsCount: 134,
    hasAvailability: true,
    waitlistDays: 4,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-013",
    media: [],
    createdAt: "2023-12-01T00:00:00.000Z",
    updatedAt: "2024-06-13T00:00:00.000Z",
  },
  {
    id: "dummy-hosp-002",
    name: "Gentle Hands Hospice Services",
    description: "Bringing compassionate end-of-life care to patients in their own homes and care facilities.",
    type: "hospice",
    address: { street: "75 Compassion Way", city: "Hillsboro", state: "OR", zipCode: "97123", county: "Washington" },
    phone: "(503) 555-1401",
    email: "support@gentlehandshospice.org",
    website: "https://gentlehandshospice.org",
    contacts: [{ name: "Rebecca Shaw", role: "Patient Care Manager", phone: "(503) 555-1402", email: "r.shaw@gentlehandshospice.org" }],
    licensure: ["OR-HOSP-2024-011", "Medicare Certified", "Medicaid Certified"],
    accreditations: ["NHPCO"],
    capacity: 40,
    currentOccupancy: 35,
    insuranceAccepted: ["Medicare", "Medicaid", "Aetna", "Kaiser Permanente"],
    careLevelsOffered: ["hospice"],
    specialties: ["End-of-Life Care", "Pain & Symptom Management", "Emotional Support", "Respite Care"],
    rating: 4.6,
    reviewsCount: 56,
    hasAvailability: true,
    waitlistDays: 2,
    acceptsMedicare: true,
    acceptsMedicaid: true,
    organizationId: "org-dummy-014",
    media: [],
    createdAt: "2023-10-10T00:00:00.000Z",
    updatedAt: "2024-05-25T00:00:00.000Z",
  },
  {
    id: "dummy-al-003",
    name: "Willow Creek Senior Apartments",
    description: "Independent and assisted living community with a vibrant social calendar and resort-style amenities.",
    type: "assisted-living",
    address: { street: "300 Willow Creek Blvd", city: "Eugene", state: "OR", zipCode: "97401", county: "Lane" },
    phone: "(541) 555-1501",
    email: "leasing@willowcreeksenior.com",
    contacts: [{ name: "Tom Henderson", role: "Community Manager", phone: "(541) 555-1502", email: "t.henderson@willowcreeksenior.com" }],
    licensure: ["OR-AL-2024-092", "Medicaid Certified"],
    accreditations: ["ALFA"],
    capacity: 110,
    currentOccupancy: 95,
    insuranceAccepted: ["Medicaid", "Humana", "UnitedHealthcare", "Blue Cross Blue Shield"],
    careLevelsOffered: ["independent-living", "assisted-living"],
    specialties: ["Wellness Programs", "Social Activities", "Transportation Services", "Fitness Programs"],
    rating: 4.0,
    reviewsCount: 48,
    hasAvailability: true,
    waitlistDays: 14,
    acceptsMedicare: false,
    acceptsMedicaid: true,
    organizationId: "org-dummy-015",
    media: [],
    createdAt: "2024-05-01T00:00:00.000Z",
    updatedAt: "2024-06-14T00:00:00.000Z",
  },
];

export function getDummyFacilities() {
  return FACILITIES;
}

export function getDummyFacilityById(id: string): Facility | undefined {
  return FACILITIES.find((f) => f.id === id);
}
