import { NextResponse } from "next/server";
import {
  DataAccessError,
  getDocuments,
  createDocument,
  logDocumentAccess,
  getValidDocumentUploadToken,
  consumeDocumentUploadToken,
} from "@/lib/data-access";
import { requireOrgPermission, authErrorResponse } from "@/lib/server-auth";
import { requireS3Config } from "@/lib/storage";
import type { DocumentCategory } from "@/types";

export async function GET(request: Request) {
  try {
    const { org } = await requireOrgPermission("documents:read");

    const { searchParams } = new URL(request.url);
    const params = {
      query: searchParams.get("q") ?? undefined,
      category: (searchParams.get("category") ?? undefined) as DocumentCategory | undefined,
      tags: searchParams.get("tags")?.split(",").filter(Boolean) ?? undefined,
      uploadedById: searchParams.get("uploadedById") ?? undefined,
      isArchived: searchParams.has("isArchived")
        ? searchParams.get("isArchived") === "true"
        : undefined,
      dateFrom: searchParams.get("dateFrom") ?? undefined,
      dateTo: searchParams.get("dateTo") ?? undefined,
      page: searchParams.get("page") ? Number(searchParams.get("page")) : undefined,
      pageSize: searchParams.get("pageSize") ? Number(searchParams.get("pageSize")) : undefined,
      sortBy: searchParams.get("sortBy") ?? undefined,
      sortOrder: searchParams.get("sortOrder") as "asc" | "desc" | undefined,
    };

    const result = await getDocuments(org.organizationId, org.role, params);
    return NextResponse.json(result);
  } catch (error: unknown) {
    if (error instanceof DataAccessError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return authErrorResponse(error);
  }
}

export async function POST(request: Request) {
  try {
    const { org } = await requireOrgPermission("documents:create");

    const body = await request.json();
    const { title, description, category, tags, notes, retentionDate, expiresAt, uploadToken } = body;

    if (!title || !uploadToken) {
      return NextResponse.json(
        { error: "Title and upload token are required" },
        { status: 400 },
      );
    }

    // Document metadata can only be registered for a key generated by the
    // upload endpoint for this organization. The one-time token binds the
    // org, storage key, file facts, and encryption material together.
    const token = await getValidDocumentUploadToken(uploadToken, org.organizationId);
    if (!token) {
      return NextResponse.json(
        { error: "Invalid, expired, or already-used upload token" },
        { status: 400 },
      );
    }

    const consumed = await consumeDocumentUploadToken(uploadToken, org.organizationId);
    if (!consumed) {
      return NextResponse.json(
        { error: "Upload token was already used" },
        { status: 409 },
      );
    }

    const { bucket, endpoint } = requireS3Config();

    const doc = await createDocument({
      title,
      description: description ?? undefined,
      category: category ?? "other",
      tags: tags ?? [],
      fileName: token.fileName,
      fileType: token.fileName.split(".").pop() ?? "unknown",
      fileSize: token.fileSize,
      mimeType: token.mimeType,
      storageKey: token.key,
      storageBucket: bucket,
      storageEndpoint: endpoint,
      encryptionKey: token.encryptionKey,
      encryptionIv: token.encryptionIv,
      checksum: token.checksum,
      retentionDate: retentionDate ?? undefined,
      notes: notes ?? undefined,
      expiresAt: expiresAt ?? undefined,
      organizationId: org.organizationId,
      uploadedById: org.userId,
    });

    await logDocumentAccess({
      documentId: doc.id,
      userId: org.userId,
      action: "UPLOAD",
    });

    return NextResponse.json(doc, { status: 201 });
  } catch (error: unknown) {
    if (error instanceof DataAccessError) {
      return NextResponse.json({ error: error.message }, { status: error.status });
    }
    return authErrorResponse(error);
  }
}
